# Generated by Django 5.0.3 on 2025-01-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=10)),
                ('direccion', models.TextField(max_length=100)),
                ('observaciones', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
